name: dayline_planner
description: Daily planner app example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.0.14
  path: ^1.8.3
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  file_picker: ^8.0.0
  fl_chart: ^1.1.1
  uuid: ^4.5.1


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#559390"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/